Update AutomationPipeline.yml

diff --git a/.github/workflows/AutomationPipeline.yml b/.github/workflows/AutomationPipeline.yml
--- a/.github/workflows/AutomationPipeline.yml
+++ b/.github/workflows/AutomationPipeline.yml
@@ -21,31 +21,25 @@ jobs:
           ls ${{ github.workspace }}
       - run: echo "🍏 This job's status is ${{ job.status }}."
 
-  Check-Site-Availability:
-    runs-on: ubuntu-latest
-    needs: Explore-GitHub-Actions
-    steps:
-      - name: Check Site Availability and Content
-        id: site_check
-        run: |
-          headers=$(curl -s -I https://phptravels.net)
-          response_code=$(echo "$headers" | head -n 1 | awk '{print $2}')
-          content_type=$(echo "$headers" | grep -i "content-type" | awk '{print $2}')
-          if [ $response_code -ne 200 ]; then
-            echo "::error::Site is down with HTTP status code $response_code"
-            exit 1
-          else
-            echo "Site is up with HTTP status code $response_code"
-            echo "Content-Type: $content_type"
-            content=$(curl -s https://phptravels.net)
-            if [[ $content == *"Expected Content"* ]]; then
-              echo "Expected content found on the page."
-            else
-              echo "::error::Expected content not found on the page."
-              exit 1
-            fi
-          fi
-        shell: bash
+- name: Check Site Availability and Content
+  id: site_check
+  run: |
+    headers=$(curl -sI https://phptravels.net -w "%{http_code}\n%{content_type}\n" -o /dev/null)
+    response_code=$(echo "$headers" | head -n 1)
+    content_type=$(echo "$headers" | head -n 2 | tail -n 1)
+    if [ "$response_code" -ne 200 ]; then
+      echo "::error::Site is down with HTTP status code $response_code"
+      exit 1
+    else
+      echo "Site is up with HTTP status code $response_code"
+      echo "Content-Type: $content_type"
+      content=$(http https://phptravels.net)
+      if ! echo "$content" | grep -q "Expected Content"; then
+        echo "::error::Expected content not found on the page."
+        exit 1
+      fi
+    fi
+  shell: bash
 
   Stop-Workflow-If-Site-Down:
     needs: Check-Site-Availability
