Update AutomationPipeline.yml

diff --git a/.github/workflows/AutomationPipeline.yml b/.github/workflows/AutomationPipeline.yml
--- a/.github/workflows/AutomationPipeline.yml
+++ b/.github/workflows/AutomationPipeline.yml
@@ -1,4 +1,4 @@
-name: Automation Trigger
+name: GitHub Actions Demo
 run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
 on: 
   push:
@@ -25,7 +25,7 @@ jobs:
     runs-on: ubuntu-latest
     needs: Explore-GitHub-Actions
     steps:
-      - name: Check Site Availability and Headers
+      - name: Check Site Availability and Content
         id: site_check
         run: |
           headers=$(curl -s -I https://phptravels.net/)
@@ -37,5 +37,21 @@ jobs:
           else
             echo "Site is up with HTTP status code $response_code"
             echo "Content-Type: $content_type"
+            content=$(curl -s https://example.com)
+            if [[ $content == *"Expected Content"* ]]; then
+              echo "Expected content found on the page."
+            else
+              echo "::error::Expected content not found on the page."
+              exit 1
+            fi
           fi
         shell: bash
+
+  Stop-Workflow-If-Site-Down:
+    needs: Check-Site-Availability
+    if: ${{ failure() }}
+    runs-on: ubuntu-latest
+    steps:
+      - name: Stop Workflow
+        run: exit 1
+
